version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moodle_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: 1234 
    volumes:
      - mysql_data:/var/lib/mysql

  moodle:
    image: docker.io/bitnami/moodle:4.5
    container_name: moodle_app
    ports:
      - '881:8080'      
      - '8443:8443'
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: mysql
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: 1234
      MOODLE_USERNAME: moodle
      MOODLE_PASSWORD: 1234
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local