version: '3.8'

services:
  apache:
    image: php:8.1-apache  
    container_name: apache
    ports:
      - "882:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - lamp_network
    depends_on:
      - mysql
    environment:
      - PHP_INI_DIR=/etc/php/7.4/apache2
      - MYSQL_HOST=mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234  
      MYSQL_DATABASE: portfolio
      MYSQL_USER: nahia
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lamp_network

networks:
  lamp_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local